### ISSUE TITLE
Make Values Nullable

### ISSUE THREAD

**Issue by dhirendrx** [vinistock/sail#388]
We are planning to use Sail to allow support/QA team make some configurable changes easily.  Some of those configs need to be set for specific case/time and then reset/unset it. The problem is, in order to unset cofig value, we need to remove the config and the team need to remember the exact config name to set it again.

We want to make values nullable, so that we can keep the attributes without any values. They will return `nil` if accessed. Add `Unset` & `Reset to default` to revert the values.

We are making the above mentioned changes inorder to support our use cases, let me know if they seems like good addition to Sail.

**Comment by vinistock** [comment]
Hello 👋

I believe it does make sense to support settings having their value set to `nil`. Currently, there's no way of indicating that a setting is unset.

However, it will be a considerable refactor, since we'll need to account for `nil` values in each type caster and in the UI.

Additionally, this will be a breaking change, since behavior might change for existing applications. For example, if an integer setting has `nil` in the database right now, the returned value is `0`, but after the changes it should actually be `nil`. So, we'll need a new major version for  it.

Let me know if you want to take a stab at implementing this.
